namespace EcoBeeApiWrapper.Enums
{
    public enum CloudCover
    {
        Sunny = 1,
        Clear = 2,
        MostlySunny = 3,
        MostlyClear = 4,
        HazySunshine = 5,
        Haze = 6,
        PassingClouds = 7,
        MoreSunThanClouds = 8,
        ScatteredClouds = 9,
        PartlyCloudy = 10,
        MixtureOfSunAndClouds = 11,
        HighLevelClouds = 12,
        MoreCloudsThanSun = 13,
        PartlySunny = 14,
        BrokenClouds = 15,
        MostlyCloudy = 16,
        Cloudy = 17,
        Overcast = 18,
        LowClouds = 19,
        LightFog = 20,
        Fog = 21,
        DenseFog = 22,
        IceFog = 23,
        Sandstorm = 24,
        Duststorm = 25,
        IncreasingCloudiness = 26,
        DecreasingCloudiness = 27,
        ClearingSkies = 28,
        BreaksOfSunLate = 29,
        EarlyFogFollowedBySunnySkies = 30,
        AfternoonClouds = 31,
        MorningClouds = 32,
        Smoke = 33,
        LowLevelHaze = 34,
    }
}
